## MODEL TRAINING

In [1]:
import pandas as pd
import numpy as np
import seaborn as  sns

In [3]:
df=pd.read_csv("stud.csv")
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.tail()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [10]:
 df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
## split the data into independent and dependent variable

In [25]:
X = df.drop('math_score',axis=1)
y = df['math_score']
print(X.shape)
print(y.shape)

(1000, 7)
(1000,)

In [33]:
## spljt the data into train test split

In [38]:
from sklearn.model_selection import train_test_split

X_train, y_train, X_test, y_test =train_test_split(X,y, test_size=0.20,random_state=42)

print(X_train.shape, y_train.shape)

(800, 7) (200, 7)

In [26]:
## applying tranformation which is 3 types

In [29]:
num_feature = df.select_dtypes(include='number').columns
cat_feature = df.select_dtypes(exclude='number').columns
print(f"we have numerical feature:{num_feature}")
print(f"we have categorical feature:{cat_feature} ")

we have numerical feature:Index(['math_score', 'reading_score', 'writing_score'], dtype='object')
we have categorical feature:Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')

In [30]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [31]:
num_pipeline = Pipeline(
    steps=[
        ("num",SimpleImputer(strategy='median')),
        ("scaler",StandardScaler())
    ]
)

cat_pipeline = Pipeline(
    steps=[
        ("cat",SimpleImputer(strategy="most_frequent")),
        ("one_hot_encoder",OneHotEncoder())
    ]
)

preprocessor = ColumnTransformer(
    [
        ("num_pipe",num_feature,num_pipeline),
        ("cat_pipe",cat_feature,cat_pipeline)
    ]
)

In [32]:
preprocessor

ColumnTransformer(transformers=[('num_pipe',
                                 Index(['math_score', 'reading_score', 'writing_score'], dtype='object'),
                                 Pipeline(steps=[('num',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler',
                                                  StandardScaler())])),
                                ('cat_pipe',
                                 Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object'),
                                 Pipeline(steps=[('cat',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('one_hot_encoder',
                                                  OneHotEncoder())]))])

In [ ]:
X_train_transformer=preprocessor.fit_transform(X_train)
X_test_transformer =preprocessor.transform(X_test)